### PR TITLE
[ADD] export function for compounds

### PR DESCRIPTION
**Pull request by oliveralka**
Add method export_compound to pyProphet.

Please let me know what you think and if you have any suggestions for improvement. 

`pyprophet export-compound --in merged_all_lin_allshuff_decoy.osw --format score_plots`
Is only working on ms2 level right now - ms1 throws an error:

```
tdensity = gaussian_kde(top_targets)
raise LinAlgError("singular matrix")
numpy.linalg.LinAlgError: singular matrix
```
This may be due to my current data (I could remove part of the function for now)

If you like to have a look at the current output I can send you a mail with the files.

Let me know if I should add some test.

### CODE REVIEW

**Comment by grosenberger** [comment]
This is a nice addition. Do you think it might make sense to add regression tests for the metabolomics data too? This would only need to cover the ``learn`` and ``export_compound`` steps.

**Comment by hroest** [comment]
:+1: looks good

**Comment by oliveralka** [comment]
I am working on adding Adducts to the OpenSWATH (tsv, pqp, osw) - after this is finished I will update this function and add regression tests.

**Comment by oliveralka** [comment]
I removed the MS1 scoring for compounds and added test for the scoring and export. 
Let me know if tests are still missing, or you would like to have them integrated differently.

**Comment by grosenberger** [comment]
Looks great, thanks for the PR!

**Pull request merged**
