### PR TITLE
[ADD] ScoreFilter 

### PR DESCRIPTION
**Pull request by oliveralka**
Add a score filter, which also supports possible score combinations for given analysis e.g. metabolomics. 

I am not sure if that fits the pyprophet data structure as it is. 
There also seems to be an incompatibility with different scoring levels (seems to work only using ms1ms2). 

@grosenberger Could you take a look and give me some pointers on how the integration could be improved. 
Afterwards, I will add some additional tests.

### CODE REVIEW

**Comment by grosenberger** [comment]
This looks very nice, thanks! Shouldn't this also work on the other scoring levels if the selected scores are present there too? Except if you use the metabolomics set of course.

**Comment by oliveralka** [comment]
It should - I will test this locally and will add additional test for the scoring filter parameter later today to this PR.

**Comment by oliveralka** [comment]
Ok, it works with the different levels. 
I had the misconception, that the MS1 scores are always "var_ms1_..." which is not the case if level=ms1. This may lead to confusion in the future when this option is used with individual levels. 
Should this be specified somewhere - without cluttering the parameter help?

**Comment by oliveralka** [comment]
@grosenberger Could you give it another look and let me know if anything should be added?

**Pull request merged**
