### PR TITLE
Export compounds scored on ms1 level (SCORE_MS1)

### PR DESCRIPTION
**Pull request by oliveralka**
ADD: MS1 to export_compound (either ms1 or ms1ms2, ms2)
ADD: New test with data for ms1, ms1ms2, ms2 scoring (test uses ms1 or ms2)
RM: Additional plot for compounds (was never used and standard plotting works as expected)

@grosenberger Please let me know what you think and if you would like to incorporate it in a different way. 

PS: I guess in the future usually ms1ms2 scoring (SCORE_MS2) is used for compounds, but If people would like to test how their decoy model performs. I think it is really helpful to have MS1 "only" scoring (SCORE_MS1) available as export and plotting as well.

### CODE REVIEW

**Comment by oliveralka** [comment]
Travis failed with: 
`error: The 'hyperopt' distribution was not found and is required by pyprophet
`

**Comment by grosenberger** [comment]
Looks great, thank you!

**Comment by grosenberger** [comment]
Hmm, it seems I was a bit too quick with merging. There still seems to be an incompatibility with the regression tests. Could you please check?

**Comment by oliveralka** [comment]
Hm, there have been probably changes in between Nov2019 and now - can you revert and I merge the current master in this branch and see where the problem is?

**Comment by oliveralka** [comment]
@grosenberger I think it has nothing to do with this PR

Python 3.7.4, pyprophet, version 2.1.4

```
pip freeze | grep hyperopt
hyperopt==0.2.1
```

`tests/test_pyprophet_score.py ..........F.                                                                                                          [ 83%]
`
```
    def test_osw_5(tmpdir, regtest):
>       _run_pyprophet_osw_to_learn_model(regtest, tmpdir.strpath, True, False, True, pi0_lambda="0 0 0", ms1ms2=True, xgboost=True, xgboost_tune=True)
```
`Command 'pyprophet score --in=test_data.osw --level=ms1 --test --ss_iteration_fdr=0.02 --pfdr --pi0_lambda=0 0 0 --classifier=XGBoost --xgb_autotune score --in=test_data.osw --level=ms1ms2 --test --ss_iteration_fdr=0.02 --pfdr --pi0_lambda=0 0 0 --classifier=XGBoost --xgb_autotune score --in=test_data.osw --level=transition --test --ss_iteration_fdr=0.02 --pfdr --pi0_lambda=0 0 0 --classifier=XGBoost --xgb_autotune' returned non-zero exit status 1.`

I get the following error when running the command:

```
Info: Learning on cross-validation fold.
Info: Learning on cross-validation fold.
Info: Learning on cross-validation fold.
Info: Learning on cross-validation fold.
Info: Learning on cross-validation fold.
Info: Finished learning.
Info: Learning on cross-validated scores.
Info: Autotuning of XGB hyperparameters.
--------------------------------------------------------------------------------                                                                           
CANT ENCODE                                                                                                                                                
--------------------------------------------------------------------------------         
```                                                                  

```
  File "/usr/local/miniconda3/envs/npy37_pyprophet_test/lib/python3.7/site-packages/hyperopt/base.py", line 399, in assert_valid_trial
    bson.BSON.encode(trial)
AttributeError: module 'bson' has no attribute 'BSON'
```
see https://github.com/hyperopt/hyperopt/issues/547

Did not work as well with hyperopt==0.2.3. 
Can you reproduce this?

**Comment by grosenberger** [comment]
Yes, that's correct, I'll try to fix it. Thank you!

**Comment by oliveralka** [comment]
Thanks! Let me know if I can test something along the way.

**Pull request merged**
